// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	mock "github.com/stretchr/testify/mock"
	pb "taskForPr/proto"
)

// CRUDService is an autogenerated mock type for the CRUDService type
type CRUDService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, req
func (_m *CRUDService) CreateUser(ctx context.Context, req *pb.CreateUserReq) (*pb.CreateUserRes, error) {
	ret := _m.Called(ctx, req)

	var r0 *pb.CreateUserRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CreateUserReq) *pb.CreateUserRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.CreateUserRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.CreateUserReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUUID provides a mock function with given fields: ctx, req
func (_m *CRUDService) GetUserByUUID(ctx context.Context, req *pb.GetUserByUUIDReq) (*pb.GetUserByUUIDRes, error) {
	ret := _m.Called(ctx, req)

	var r0 *pb.GetUserByUUIDRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.GetUserByUUIDReq) *pb.GetUserByUUIDRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.GetUserByUUIDRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.GetUserByUUIDReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserByUUID provides a mock function with given fields: ctx, req
func (_m *CRUDService) UpdateUserByUUID(ctx context.Context, req *pb.UpdateUserByUUIDReq) (*pb.UpdateUserByUUIDRes, error) {
	ret := _m.Called(ctx, req)

	var r0 *pb.UpdateUserByUUIDRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.UpdateUserByUUIDReq) *pb.UpdateUserByUUIDRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.UpdateUserByUUIDRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.UpdateUserByUUIDReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
